inclusive-design/wecount.inclusivedesign.ca

package.json
This PR adds the `--fail-on-error` flag to the generate command, which will cause the build to fail if any errors occur during the static site generation process.
=> fix: generate error should fail CI (resolves #37)

store/actions.js
Uses WordPress REST API's media `source_url` parameter to ensure that image URLs are secure.
=> fix: mixed content errors (resolves #74)

assets/css/abstracts/_abstracts.scss, assets/css/abstracts/_variables.scss, assets/css/main.scss, nuxt.config.js, package-lock.json, package.json
This PR uses [nuxt-webfontloader](https://github.com/Developmint/nuxt-webfontloader) to add the Fira Sans webfont and applies it by setting the `$family-sans-serif` [initial variable](https://bulma.io/documentation/customize/variables/#initial-variables) for Bulma.
1. Visit the deploy preview.
**Expected behavior:** Fira Sans is used throughout the site.
- https://github.com/Developmint/nuxt-webfontloader#adding-google-fonts-with-font-display-option
- https://bulma.io/documentation/customize/variables/#initial-variables
- Resolves #77.
=> feat: add Fira Sans webfont (resolves #77)

assets/css/main.scss, nuxt.config.js, package-lock.json, package.json, pages/tools.vue
resolves #102
Removed the Bulma framework
1. global search of "bulma"
2. Make sure nothing comes up
Bulma commands do not work
I left `@nuxtjs/style-resources` because it may be used for other styling
resolves #102
=> feat: remove bulma

assets/css/components/_pagination.scss, components/Pagination.vue
To resolve https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/127.
Now the ellipsis displays at the correct place on the pagination.
1. Run "npm run dev" to start the website
2. Click "news and views" -> select one post
3. The pagination shows up underneath the post. 
The ellipsis should be at the correct spot.
=> Issue-127: Fix the ellipsis position for the pagination.

pages/search/_query/index.vue, shared/DataFetcher.js, shared/Utils.js
To resolve https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/131.
Clicking a site page link on the search result now leads to the actual page
Follow steps described in https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/131 to reproduce the problem
The problem should be fixed: Clicking a site page link on the search result now leads to the actual page.
=> Issue-131: Clicking a site page link on the search result now leads to the actual page

assets/css/layout/_footer.scss
To resolve https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/156.
Fix the focus/hover styling with footer SVGs on mobile devices.
Follow steps on the ticket https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/156 to reproduce the problem.
**Expected behavior:** The styling should look like the screenshot of the expected behavior in the https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/156.
=> Issue-156: Fix the focus/hover styling with footer SVGs on mobile devices

nuxt.config.js, store/actions.js
WordPress uses a default category (ID: 1) for new posts. When I added the COVID-19 response post I realized that we set up the default category as "News". I think the default category should be "Views". So I've edited the categories in the CMS to change ID 1 to "Views" and ID 8 to "News". This pull request makes the corresponding change in Nuxt.
1. Visit News and Views pages.
**Expected behavior:** See "The Importance of Peripheral Vision" and "Continuing Our Work During COVID-19" on Views. See other posts on "News".
=> fix: swap categories for News and Views

pages/search/_query/index.vue
Adds the appropriate ARIA role to search results message.
1. Perform a search.
**Expected behavior:** The paragraph that communicates how many results were found includes the `role="status"` attribute.
Resolves #173.
=> fix: add ARIA role to search results message (fixes #173)

components/NewsGrid.vue, components/NewsItem.vue, shared/DataFetcher.js
This PR uses the custom WordPress excerpt for post previews in the `<NewsItem />` component.
1. Identify a WordPress post with a custom excerpt, e.g. https://wecount-cms.inclusivedesign.ca/wp-json/wp/v2/posts/210.
2. Find it on the Views page.
**Expected behavior:** The excerpt shown in the API is used for the preview text in the grid.
- https://wordpress.org/support/article/excerpt/
Resolves #172.
=> feat: use excerpts from WordPress API (resolves #172)

components/PostArticle.vue
The tag area on single views page should only show when there are tags.
Since the WordPress API for the development is not set up yet and all views posts production data have tags. The test step is by modifying the data fetcher component:
1. Checkout this branch;
2. Modify [this line](https://github.com/cindyli/wecount.inclusivedesign.ca/blob/fix/when-no-tags/shared/DataFetcher.js#L24) to `tags: [],`;
3. In a terminal, run "npm run dev" to start the site locally;
4. Go to "Views" -> select a single article;
5. The tags area underneath the article content should not show.
6. Undo the modification at step 2;
7. Go to "Views" -> select a single article;
8. The tags area underneath the article content should show.
See above.
=> Issue-177: Not to show the tag area when there's no tags.

components/Footer.vue
Using a `<nuxt-link>` for the Netlify credit broke the link. This PR uses a standard `<a>` link.
1. Visit deploy preview.
2. Follow the link to Netlify.
**Expected behavior:** It works.
=> fix: resolve broken Netlify link

.github/CONTRIBUTING.md, README.md, package-lock.json, package.json
Expands README to include contributing instructions.
- Resolves #182.
=> docs: add contributing guide (resolves #182)

.browserslistrc, nuxt.config.js
Adds a `.browserslistrc` file which will be used by [PostCSS](https://nuxtjs.org/api/configuration-build/#postcss).
1. From the project root, run `npx browserslist`.
**Expected behavior:** List of browsers should match [our desired configuration](https://browserl.ist/?q=%3E+1%25).
Why not use 'browsers' in `preset` config? https://github.com/csstools/postcss-preset-env#browsers
> The `browsers` option should only be used when a standard browserslist configuration is not available.
- Resolves #188.
=> feat: configure PostCSS/Autoprefixer (resolves #188)

assets/css/layout/_footer.scss, components/Footer.vue, components/Header.vue, components/NavBar.vue, shared/DataFetcher.js, shared/Utils.js, store/actions.js
To resolve https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/170.
Navigation menus on the header and footer are auto generated based on the WordPress API response.
1. The navigation menu on the header shows 4 items: About, Inclusion Challenges, News, Views;
2. Remove `style="display: none;"` that hides the nav menu on the footer;
3. The nav menu on the footer shows 5 items: Home and 4 items described in 1.
The footer css has been adjusted to work with the current 5 menu items instead of 7 that was expected in the design. The footer css needs to be revisited every time when a menu item is added or removed.
The navigation menu should look the same as what's in the current dev branch.
=> Issue-170: Auto generate navigation menus based on the API response.

README.md, assets/config.js
Now that https://wecount-dev.inclusivedesign.ca is set up, this PR configures all builds except for production builds to use this new dev endpoint.
1. Edit some prominent content on https://wecount-dev.inclusivedesign.ca.
2. Run `npm run dev`.
3. Confirm that the edited content appears. 
4. Run `CONTEXT=production npm run generate`.
5. Run `npx serve dist` to preview the generated site.
6. Confirm that the content from https://wecount-cms.inclusivedesign.ca appears.
- Resolves #166.
=> chore: add dedicated development endpoint for API (fix #166)

assets/css/layout/_footer.scss, components/Footer.vue, components/Header.vue, components/NavBar.vue, shared/DataFetcher.js, shared/Utils.js, store/actions.js
To resolve https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/208.
Revert the auto generation of the navigation menu.
1. Start the site and verify the navigation menu.
**Expected behavior:**
The navigation menu should look
=> fix: revert the auto generation of the navigation menu

src/scss/layout/_header.scss
Use attribute selector to style the current link instead of `.nuxt-link-active`
1. run `npm run build`
2. click around on link in the nav
3. the current link should have the following style: `border-bottom: rem(2) solid $white;`
The current link should have the following style: `border-bottom: rem(2) solid $white;`
~~`npm run start` is not running due to:~~
```
sh: concurrently: command not found
```
~~`npm run build` is not running due to:~~
```
sh: cross-env: command not found
```
_UPDATE:_
After running `npm install` these commands are now working but stylesheets are not being applied in local development mode (after running `npm run start`).
resolves #213
=> Style nav item

src/transforms/parse.js
Implement a side menu for view posts
1. run `npm run build`
2. Go to Views page
3. Click on the 3rd last or 4th last post (_Another test post_ or _Test views post_)
4. Make sure the side menu is to the left side
5. Click on side menu links
The links should jump to the section of the current webpage with the corresponding h2 subtitle.
N/A
resolves #222 closes #222
=> fix: added side menu to post articles

src/transforms/parse.js
Readding  h1 title to view side menu
1. run `npm run build`
2. Go to Views page
3. Click on the 3rd last or 4th last post (_Another test post_ or _Test views post_) or about or inclusive-challenges page
4. Make sure the side the title of the page is the first link in the side menu
This should jump to the section of the webpage where the title of the page is at the very top
N/A
close #222
=> Re added h1 title to view side menu

src/_includes/components/pagination.njk, src/_includes/layouts/tag.njk, src/_includes/svg/next.svg, src/_includes/svg/prev.svg, src/js/search.js, src/js/utils.js, src/scss/components/_pagination.scss, src/search.njk
Add the pagination to the search result page.
1. Search by a keyword, for example, an empty space " ";
2. The search status text shows: Search results: " " (Note the double quotes around the empty character);
3. Only 10 results show up;
4. The pagination is shown underneath the result. Clicking through some of them to check if page url and content are directed correctly.
=> feat: add pagination to the search page

.github/CONTRIBUTING.md
The format for pull request titles should be defined in .github/CONTRIBUTING.md
=> fix: define the format of pull request titles in the contributing doc (resolves #249)

src/_includes/components/brand.njk
Remove the `tabindex` attribute from the WeCount logo.
1. Open any web page;
2. Using the "tab" key to move the mouse focus around the page.
The first focus should be on the "show preferences" button, then the WeCount logo.
=> fix: remove tabindex (resolves #257)

src/scss/components/_pagination.scss
To resolve #255.
The change of UIO line space value no longer affects the position of ellipses on the pagination.
1. Go to the "views" page;
2. Open UIO and increase the line space value;
3. Scroll to the pagination area.
The position of ellipses on the pagination doesn't shift and remain at the same position as when the line space value is 1.
=> fix: the change of UIO line space value no longer affects the pagination (resolves #255)

src/scss/layout/_footer.scss
To resolve #254.
Footer texts respond to the change of UIO line space value.
1. Open any webpage;
2. Scroll to the footer;
3. Footer texts look good;
4. Open UIO and increase the line space value;
5. Scroll to the footer to check the line space of footer texts.
The line space of footer texts increase and respond to the change of the line space value.
=> fix: remove line-height definitions from footer elements (resolves #254)

src/_includes/layouts/base.njk, src/js/uio.js, webpack.mix.js
To resolve #253.
Set the minimum value for the UIO line space to 1.
1. Go to any webpage and open UIO;
2. The value in the UIO line space input field is 1;
3. Cannot use "-" button to the left of the input field to decrease the value;
4. Select a high or low contrast theme;
5. Go to the "news" page
News titles are shown properly without any cut-off on texts.
=> fix: set the minimum value for UIO line space to 1 (resolves #253)

src/scss/layout/_footer.scss
Display the footer in the desktop layout starting from the ipad size screens.
1. Open any web page;
2. Switch to the responsive design mode and pick "ipad";
3. Scroll to the footer. The footer should be displayed in the desktop layout;
4. Pick a screen that is smaller than the ipad. The footer should be displayed in the mobile layout;
5. Pick a screen that is larger than the ipad. The footer should be displayed in the desktop layout.
See above.
=> fix: display the footer in the desktop layout from the ipad size screen

src/js/uio.js, src/scss/abstracts/_mixins.scss, src/scss/base/_base.scss, src/scss/components/_aside.scss, src/scss/components/_cards.scss, src/scss/components/_news-and-views.scss, src/scss/components/_pagination.scss, src/scss/layout/_footer.scss, src/scss/layout/_header.scss, src/scss/layout/_layout.scss, src/scss/vendors/_vendors.scss
Implement the style for UIO table of content according to [the design](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website).
1. Go to the deploy preview and turn on UIO "table of content";
2. Go through different type of pages to make sure the implementation matches the design;
A few clarification on top of the design:
1. The list style for h1 is solid circles, for other heading levels are empty circles;
2. The table of content for "news" page also list all post titles;
3. These items should be excluded from the table of content:
* All headings on the footer
* The "Tags" heading on the views post pages
=> fix: Implement the style for UIO table of content (resolves #232)

src/_data/social.json
Fix the broken facebook link.
1. Open any page;
2. Scroll to the bottom and click on the facebook link.
The link should take the page to [the WeCount project facebook page](https://www.facebook.com/We-Count-Project-103084404745143/).
=> fix: update facebook URL for WeCount project (resolves #275)

src/_includes/components/grid-item.njk, src/page.njk, src/pageItem.njk, src/post.njk, src/scss/abstracts/_mixins.scss, src/scss/components/_news-and-views.scss, src/scss/components/_post-article.scss, src/search.njk, src/viewsItem.njk
Support the display of featured images on the grid of "Views" page and post articles.
1. Go to "Views" page;
2. Featured images are displayed in the grid and match the design; articles that don't have featured images display placeholder images;
3. Select an article that has the featured image;
4. The featured image should be displayed on the article page and match the design;
5. Go back to the "Views" page and select a post that doesn't have the featured image;
6. No images should be shown on the article page.
=> feat: support featured images (resolves #281)

src/scss/abstracts/_mixins.scss
Non-views posts on search results don't keep preview image blocks
1. Search for the keyword "ai";
2. Non-views posts on the search result should not keep space for preview images.
See above.
=> fix: non-views posts on search results don't keep preview image blocks

src/scss/layout/_header.scss
The left border of the search container no longer overlaps with the menu bar on the desktop view when a UIO theme is selected.
1. Open UIO and select a theme. Make sure the browser is on the desktop view;
2. The left border of the search container no longer overlaps with the menu bar;
3. Switch to the mobile view;
4. The search should look and work properly.
See above.
=> fix: the search container doesn't overlap with the view item on desktop (resolves #288)

src/scss/abstracts/_mixins.scss
Placeholder preview images should show when a UIO theme is selected
1. Open UIO and select a theme;
2. Go to the "Views" page, select page 11;
Placeholder preview images should adjust colors to the selected theme.
=> fix: placeholder preview images should show when a UIO theme is selected (resolves #291)

src/_data/social.json
To change the url of the LinkedIn icon to https://www.linkedin.com/company/we-count/
1. Scroll to the footer;
2. Click the LinkedIn icon in the "social media" section.
The page should be taken to this URL: https://www.linkedin.com/company/we-count/
=> fix: change the url of the LinkedIn icon (resolves #294)

src/_includes/components/nav-menu.njk, src/_includes/components/search-container.njk, src/js/main.js, src/scss/abstracts/_mixins.scss
Fix html validation errors and warnings.
1. Go to [W3C html validator](https://validator.w3.org/);
2. In "Validate by URI" tab, enter "https://dev--wecount.netlify.app/" and click the "check" button;
3. There shouldn't be any errors or warnings;
4. Try other WeCount URLs and make sure no validation errors and warnings;
5. Test the search container in the header to make sure: 
* It works properly with the search on desktop and mobile layouts
* It responds to UIO theme change
See above
=> fix: fix html validation errors and warnings (resolves #302)

src/utils/data-fetcher.js
I noticed that on the Views page, the posts were not in the correct reverse chronological order: https://wecount.inclusivedesign.ca/views/
This appears to have been a bug in the data fetcher utility. When it was created it was set up to fetch items in reverse chronological order based on date modified. However, this means that if a post is edited it will be moved to the start of the list— so adding featured images to old Views posts had reordered them.
This PR addresses the issue by changing the `orderby` parameter to `date` (date created) instead of `modified`.
1. Check out this branch.
2. Run `npm run start`.
3. Visit News and Views pages.
**Expected behavior:** Content is shown in reverse chronological order based on publication date.
=> fix: news and views should be sorted by date published, not modified

src/page.njk, src/post.njk, src/scss/components/_cards.scss, src/scss/components/_post-article.scss
Heading elements on a page should be in a sequentially-descending order.
1. Go to "Home" page;
2. Open the page source, heading levels on the page should be h1 -> h2;
3. Go to a post page and check the page source, heading levels should be h1 -> h2.
See above.
=> fix: heading elements should be in a sequentially-descending order (resolves #309)

src/scss/abstracts/_mixins.scss, src/scss/base/_base.scss
Added proper styling to download buttons.
1. Go to the deploy preview.
2. Go to the Views page then select the "Journeys through the Digital Innovation Appendix of the Master Innovation and Development Plan" post.
3. Observe the styling of the download button.
The download button should have the same style as all other buttons as specified in [Figma](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website?node-id=1622%3A5648)
Issues with figures will be resolved in #137 
resolves #314
=> fix: added styling to download buttons (resolves #314)

package-lock.json, src/scss/abstracts/_mixins.scss, src/scss/components/_post-article.scss
Replaced `border` with `box-shadow` for tags.
1. Go to deploy preview
2. Go to views page then navigate to a post with tags at the bottom. (For example "The Importance of Peripheral Vision")
3. Turn on uio contrast themes (white foreground/black background would be best, this is uio contrast theme option number 2)
4. Hover/focus over the tags and confirm they no longer look like they're overlapping
No overlapping of the outline should occur while hovering/focusing on tags.
N/A
resolves #316
=> fix: use box shadow instead of border on tags (resolves #316)

src/scss/abstracts/_mixins.scss
Box shadows for the card links on the home page now respond to the current link color.
1. Go to the home page;
2. Open UIO and test each contrast theme.
The box shadows around link cards respond to the current link color.
=> fix: adjust box shadows for the card links on the home page (resolves #319)

src/scss/layout/_header.scss
Adjusted margin and padding of header nav links to stop overflow of header nav search in iPad Pro view
1. Go to deploy preview
2. Inspect page in iPad Pro view
3. Observe header nav search
Ensure header nav search is not overflowing outside of header nav.
N/A
resolves #325
=> fix: adjusted padding and margin for header nav links (resolves #325)

src/_includes/components/filter.njk, src/js/views-dynamic-handler.js, src/views.njk
Provide proper names for expand buttons on the "Views" landing page.
1. Go to "Views";
2. Use screen reader (for example VoiceOver on Mac) to check the name of expand buttons are correctly read after performing expanding or collapsing actions;
3. Run lighthouse report for this page, the accessibility score should be 100.
See above.
=> fix: provide proper names for expand buttons on the "Views" landing page (resolves #328)

src/scss/vendors/_vendors.scss
UIO button and its panel will be in the same viewport width as the main page.
1. Go to any page and use responsive design mode to set a large screen width such as 3000;
2. UIO button should be above the search container on the nav bar;
3. Open UIO;
4. The UIO panel should use the similar viewport width as the main page.
See above.
=> fix: uio button and its panel are in the same viewport as the main page (resolves #326)

src/scss/vendors/_vendors.scss
Prevents UIO panel from being cut off as width of screen increases.
1. Go to deploy preview
2. Inspect webpage in responsive view
3. Click on the UIO tab at the top of the webpage (it has the text _+ show preference_)
4. Expand the width of the screen to greater than 3000px
5. View the UIO panel
UIO panel should fill the width of the screen.
N/A
resolves #332
=> fix: anchored uio tab above hearder nav search bar (resolves #332)

src/scss/components/_filter.scss
Tag filter button labels appears on single for all screen sizes.
1. Go to deploy preview
2. Navigate to views page
3. Inspect page using Galaxy Fold screen
4. Observe tag filter button labels 
Tag filter button labels should occupy a single line.
N/A
resolves #338
=> fix: applied inline flex to tag fiter label span (resolves #338)

src/_includes/components/filter.njk, src/views.njk
Improve the appearance and text for the "Search Filters" on the views landing page.
1. Go to Views landing page and check the title of "Search Filters";
2. The appearance is in h3 style;
3. Search/Filter and check again.
1. Text should be "Search Filters";
2. The appearance is in h3 style.
=> fix: improve the text for "search filters" on the views landing page

src/scss/components/_filter.scss
Long label texts on the search filter now have hanging indent.
1. Go to the views landing page, open "search filter";
2. Switch to mobile view;
3. Long labels are displayed in multiple lines should have hanging indent after the first line;
4. Test with UIO settings; the hanging indent should be maintained.
See above.
=> fix: add hanging indent for label texts in the search filter (resolves #354)

.github/workflows/main.yml, eleventy.config.js, netlify.toml, package-lock.json, package.json, src/_data/env.js, src/_includes/components/nav-menu.njk, src/_includes/components/workshop.njk, src/initiatives.njk, src/scss/abstracts/_mixins.scss, src/scss/components/_components.scss, src/scss/components/_initiatives.scss, src/transforms/parse.js, src/utils/data-fetcher-airtable.js, src/utils/data-fetcher-wp.js
Re-implement the Initiatives page by fetching data from Airtable. This is the first step for adding the comment area for each workshop.
Note that for now clicking each workshop image leads to "Page not found". The individual workshop page will be implemented under #350 ticket.
1. Go to "Initiatives" page;
1. The workshops displayed on the page should be fetched from the "WeCount_DEV" table from Airtable;
2. The page layout should match [the Figma design](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website).
=> Feat: Implement the Initiatives page by fetching data from Airtable

src/scss/layout/_layout.scss
This PR implements a CSS utility to blur images which have either a missing alt tag or an alt tag beginning with `This image has an empty alt attribute` (see #389). Images with alt tags which are present but empty are assumed to be decorative and are unaffected. 
1. Check out this branch.
2. Run `netlify dev`.
3. Visit the badges page.
**Expected behavior:** Badge images are blurred.
Adapted from https://github.com/platform-coop-toolkit/pinecone/issues/230.
Not applicable
=> feat: blur images with missing or unhelpful alt tags

src/scss/components/_pagination.scss
Adjust the color of pagination links according to the figma design.
1. Check [the report of "lighthouse CI - Mobile"](https://github.com/inclusive-design/wecount.inclusivedesign.ca/pull/293/checks?check_run_id=1130461284) generated by [the lighthouse CI pull request](https://github.com/inclusive-design/wecount.inclusivedesign.ca/pull/293);
2. Accessibility score of a few pagination links is dropped from 100 to 98.
3. Run lighthouse - Mobile report with pages that have problems with the fix.
Accessibility scores should be back to 100.
=> fix: improve the color contrast of pagination links (resolves #397)

README.md, functions/comments.js, src/_data/env.js
Allow to define different moderator emails as environment variables for the production and the development websites.
1. Follow the section "Test the website with Netlify Functions" in README to run Netlify dev environment locally. This allows the tester to use two own email addresses to test;
2. Simulate the development site and test:
* Follow commands in "Test the website with Netlify Functions" to start a simulation of a development site;
* Go to the workshop page and post a comment; 
* The email address defined in EMAIL_TO_DEV should receive an email;
* Check Airtable "WeCount_DEV" base, the new comment should appear in the "comments" table.
3. Simulate the production site and test:
* In the terminal, issue this command `export CONTEXT=production`;
* Follow commands in "Test the …
=> feat: allow to define different moderator emails for production and dev sites (resolves #403)

README.md, src/scss/abstracts/_mixins.scss, src/scss/components/_filter.scss, src/scss/components/_search-container.scss, src/scss/layout/_header.scss
Use `content` attribute to display filter checkmarks as contents so that their positions are auto-adjusted when UIO line height changes.
1. Go to the Views page, open the filter section, click a checkbox, a checkmark shows;
2. Open UIO, gradually increase the line height;
3. Check the position of the checkmark.
The position of checkmarks look good.
=> fix: custom checkmarks display inside checkboxes when the line height changes (resolves #408)

src/scss/layout/_layout.scss
Badge images should be smaller and displayed in proportion.
1. Go to the Badges page
The size of badges images are good.
@uttaraghodke, can you take a look at badge images in the deploy preview and let me know if they look better? Thanks.
=> fix: adjust the size of badge images (resolves #413)

src/scss/components/_cards.scss
Decrease tile heights to move tile image positions.
@uttaraghodke, can you check image positions in this deploy preview and let me know how they look? Thanks.
=> fix: adjust the position of images on home page tiles (resolves #411)

src/scss/layout/_layout.scss
Badge images should remain at the right of the text on mobile screens
1. Go to the deploy preview of this pull request;
2. Switch to the responsive mode;
3. Go to the badges page.
Badge images should remain at the right of the text on mobile screens.
=> fix: fix positions of badge images on mobile screens (resolves #419)

.github/CONTRIBUTING.md, README.md
Updated references to the "master" branch to "main". I couldn't test the building of the site though because I don't have an Airtable API key.
=> docs: rename master to main

src/page.njk, src/scss/components/_badges.scss, src/scss/components/_components.scss
Reduce the space between h3s and their contents on the badges page.
1. Go to the badges page;
2. Compare the deploy preview with the dev or production sites on the space right below h3s.
In the deploy preview, the space below h3s should be reduced to a reasonable size.
=> fix: reduce the space between h3s and their contents on the badges page (resolves #425)

src/utils/data-fetcher-airtable.js
The build or deploy no longer fails when there are empty workshop records.
1. Go to [Airtable](https://airtable.com/) WeCount_DEV base and make sure there is at least one empty record in "workshops" table.
2. Follow [the readme instruction](https://github.com/inclusive-design/wecount.inclusivedesign.ca/#how-to-run) to build the website locally.
1. The build completes successfully.
2. Go to the Initiatives page, workshops are listed correctly.
=> fix: the build/deploy no longer fails when there are empty workshop records (resolves #431)

src/_includes/components/workshop.njk
Use the workshop title as the alt text for the cover image when the alt text is not defined in the Airtable.
1. Check Airtable to find workshop records that have cover image uploaded but the image alt text is not defined;
2. Go to the Initiatives page;
3. The workshops identified in step 1 should have their workshop title used as the alt text for cover images;
4. All workshop cover images should have alt texts;
5. Run lighthouse report;
6. The score for accessibility should be 100.
See above.
=> fix: use the workshop title when the image alt text is not defined (resolves #436)

src/page.njk, src/scss/abstracts/_mixins.scss, src/scss/components/_advisory-panel.scss, src/transforms/parse.js
Adjust the styling of the advisory panel page based on [the figma design](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website?node-id=2257%3A0). Refer to [the issue](https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/440) about details to be adjusted.
1. Go to the Advisory Panel page;
2. Make sure the adjusted styling matches the design;
3. Test with UIO and make sure the adjusted styling corresponds correctly.
See above.
=> feat: adjust the styling of the advisory panel page based on the design (resolves #440)

src/_includes/components/workshop.njk, src/scss/abstracts/_mixins.scss, src/scss/components/_initiatives.scss, src/utils/data-fetcher-airtable.js
Add "register here" button for workshops on the Initiatives page. The design for it can be found in [the figma](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website?node-id=1881%3A3695)
1. Check Airtable "wecount_dev" base. In the "workshops" table, some workshops have URLs defined in "registration_url" field, some don't have;
2. Go to the Initiatives page, workshops have "registration_url" defined in Airtable have "register here" buttons displayed. The style of this button should match the design;
3. Test with UIO and the button should respond correctly.
See above.
=> feat: add "register here" button for workshops on the Initiatives page (resolves #441)

src/_includes/components/workshop.njk, src/scss/abstracts/_mixins.scss, src/scss/components/_initiatives.scss, src/utils/data-fetcher-airtable.js, src/workshop-comments.njk
Applied changes described in https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/446 for the Initiatives page.
1. Go to Airtable -> base "WeCount_DEV", "preview_alt_text" and "cover_alt_text" fields should be in place;
2. Go to the initiatives page, check:
* Workshop preview images are no longer links;
* For workshops that have "preview_alt_text" set in the Airtable, `alt` value for this workshop preview image should have been set to the alt value;
* For workshops that don't have "preview_alt_text" set in the Airtable, this workshop preview image tags should have `role="presentation".
3. Click on a workshop title to go to the workshop information page. Check:
* If this workshop has a cover image uploaded in the Airtable, the cover image should be displayed on the page …
=> feat: improve workshop preview images on the initiatives page (resolves #446)

src/page.njk
On the Home page, update the tile link of "participate in challenges" to https://wecount.inclusivedesign.ca/initiatives/.
1. Click the tile on the home page
It needs to the initiatives page.
=> fix: update the tile link to participate in challenges

src/page.njk
Change the home tile label "find inclusive data tools" to "Search the We Count Library".
1. Check the home page.
The label should have been updated.
=> fix: update one home tile label (resolves #454)

src/js/utils.js
A custom field "author" is added in WordPress for defining a different author other than the actual post creator. This only applies to posts in the Views category. This pull request is to fetch and display authors of Views posts from this custom field.
1. Go to the WordPress dev site;
2. Check the author of "test post 100": the actual post author is "Cindy Li" while the custom author is "Test Author";
3. Go to the Views page;
4. The author displayed for "test post 100" is "Test Author".
See above.
=> feat: views articles use author names defined in the custom author field (resolves #452)

src/_includes/components/workshop.njk, src/scss/abstracts/_mixins.scss, src/scss/components/_initiatives.scss, src/utils/data-fetcher-airtable.js
Make each tile on the Initiatives a link to the tile event full description page. Titles on the tiles are no longer links.
1. Check Airtable "WeCount_dev" base;
2. The "registration_url" field should have been removed;
3. Go to the Initiatives page;
4. Each tile is a link to the tile event full description page;
5. Titles on the tiles are no longer links.
See above.
=> fix: make initiative tiles links (resolves #456)

src/scss/components/_initiatives.scss
Remove preview images from the mobile view of the Initiatives page based on the modified design at [the figma](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website?node-id=1881%3A3695).
1. Go to the Initiatives page;
2. On the desktop view, workshop preview images are displayed according to the design;
3. Switch the page to the mobile view, preview images are no longer displayed.
4. The behavior should match what's on [the figma design](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website?node-id=1881%3A3695).
See above.
=> fix: remove preview images from the mobile view of the Initiatives page (resolves #458)

eleventy.config.js, src/_includes/components/footer-nav.njk, src/_includes/components/nav-menu.njk, src/js/utils.js, src/news.11tydata.js, src/news.njk, src/page.njk, src/searchIndex.njk, src/views.11tydata.js, src/views.njk
Allow editing News and Views intro texts via WordPress.
1. Go to News or Views page;
2. Check the intro texts defined in WordPress under "News" and "Views" pages;
The intro texts displayed at the top of the News or Views page should match the corresponding in the WordPress.
=> feat: allow editing news/views intro texts via WordPress (resolves #464)

src/_includes/layouts/base.njk
This PR adds Netlify's [Identity](https://docs.netlify.com/visitor-access/identity/) services script to the home page, which will allow invited users to set or reset their account passwords.
1. Load the home page.
**Expected behavior:** See that the Netlify Identity script is loaded in the footer.
=> feat: add Netlify Identity script to home page to allow registration

src/admin/cms.js
Ensures that uploaded images are always previewed properly.
1. Run `npm start`.
2. From the CMS, create a new initiative and upload a cover image.
**Expected behavior:** The image should appear in the preview.
Uses `getAsset()`: https://www.netlifycms.org/docs/customization/#registerpreviewtemplate
Resolves #472.
=> fix: handle image previews for unpublished uploads (fix #472)

src/_includes/layouts/base.njk
Currently, when a user logs in on the home page and they have the appropriate role, a link to the CMS is appended to the home page footer. If the user logs out the link persists in the DOM. This PR removes the link when a user logs out to avoid possible confusion.
1. Log in from the home page.
2. Log out again.
**Expected behavior:** The administration link appears upon login and disappears upon logout.
=> feat: remove link to administration when user logs out

src/admin/cms.js
Fix the broken preview panel when creating a new Views entry.
1. Login and go to Netlify CMS admin page;
2. Select "Views" collection, click "New Views Entry" button;
The preview panel at the right should display a proper preview panel instead of reporting the type error.
=> fix: fix the broken preview panel when creating a new Views entry (resolves #576)

src/scss/components/_map.scss
Adjust the style when displaying a disclaimer.
1. Check the map and disclaimer on desktop and mobile views.
The map and disclaimer should look ok and work ok.
=> fix: adjust style for displaying a disclaimer

src/_includes/layouts/resourceDetail.njk
This pull request fixes a typo in the resources detail pages.
1. Go to the Resources page
2. Click on any resource tile
**Expected behavior:** The "Readability" field should say "Readability" and not "Redability"
=> fix: correct typo in resource detail template

src/_includes/components/header.njk, src/_includes/components/idrc-indicator.njk, src/scss/components/_brand.scss, src/scss/components/_components.scss, src/scss/components/_idrc-indicator.scss, src/scss/layout/_header.scss
Add the IDRC project indicator banner to the header.
Resolves https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/932.
1. Open any page;
2. The IDRC project indicator banner should shown on the header and match [the design](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website?node-id=4016%3A10803).
=> feat: add ISRC project indicator banner to the header (resolves #932, 934)

package-lock.json, package.json, src/scss/abstracts/_reset.scss, src/scss/base/_base.scss, src/scss/components/_filter.scss, src/scss/components/_pagination.scss, src/scss/components/_resources.scss, src/scss/layout/_layout.scss
Migrate from CSS normalisation library sanitize.css to "modern CSS reset"
**Expected behavior:**
Hovering over any text element should show the standard "caret" cursor indicating selectable text
Resolves #939
=> feat: move from sanitize to modern-css-reset (resolves #939)

src/scss/base/_base.scss, src/scss/components/_pagination.scss
As part of our transition to modern-css-reset in https://github.com/inclusive-design/wecount.inclusivedesign.ca/pull/940 we lost a few styling rules from our reset, including those which applied default HTML list styling. As a result, unordered lists in markdown appear without any styling as shown in the following screenshot
View a page with a bulleted list such as https://wecount.inclusivedesign.ca/views/pluralistic-data-infrastructure/
**Expected behavior:**
List should appear styled as a default HTML unordered list
=> fix: restore bullet styling which was lost in transition to modern-css-reset

.github/workflows/lint.yml
Right now the lint GitHub Action only runs when lintable files (JS, MD, SCSS) are modified. This PR will also trigger the lint action when the package.json and/or package-lock.json files change so that we can better assess the impact of, say, a Dependabot update to Stylelint.
Not applicable; the GitHub Action which lints files will now run on PRs like https://github.com/inclusive-design/wecount.inclusivedesign.ca/pull/1402.
=> chore: run lint action when NPM dependencies change

.husky/post-checkout, .husky/post-commit, .husky/post-merge, .husky/pre-push
This PR removes git hooks related to Netlify Large Media (see #1602).
This will have no impact on building or deploying the site.
#1602
=> fix: remove Husky hooks for Git LFS

src/scss/layout/_layout.scss
Fixes the vertical alignment issue for image and text widget.
1. Go to the admin panel
2. Create a new page using Image and text widget with image position `left`
3. Change the vertical alignment to different options
4. See the changes get applied correctly on the preview
=> fix: vertical alignment issues for Image and Text widget

netlify.toml, src/_includes/components/footer.njk, src/_includes/layouts/base.njk, src/assets/styles/components/_components.scss, src/assets/styles/components/_identity.scss
This PR removes the role-based redirect away from the admin page for Netlify Identity users without the administration role. Open registration has been disabled for this site so this is no longer necessary and will resolve #906.
1. Visit /admin/
**Expected behavior:** You are prompted to log in.
Resolves #906.
=> feat: remove role-based authentication check (resolves #906)

eleventy.config.js, package-lock.json, package.json, src/_includes/layouts/base.njk, src/admin/config.yml, src/assets/styles/base/_base.scss, src/assets/styles/layout/_layout.scss, src/shortcodes/youtube.js
This PR uses https://github.com/paulirish/lite-youtube-embed for the YouTube shortcode, which improves performance and privacy for YouTube embeds.
1. `npm ci`
2. `npm start`
**Expected behavior:** Visit pages with YouTube embeds and test to make sure that they behave as expected.
=> feat: use lite-youtube-embed for YouTube videos

src/assets/styles/base/_base.scss, src/shortcodes/expander.js
Add a class for the expander toggle button, and don't apply generic buttons styles on its ::before.
1. Go to Advisory Panel
2. See the expander buttons have correct style
**Expected behavior:**
=> fix: expander style issue

src/assets/styles/components/_cards.scss
Remove border of the cards in default theme, and only apply border in different UIO themes.
1. Check that cards in main page don't have border
2. Change UIO themes and see cards have border
=> fix: remove border in default theme

src/assets/styles/components/_aside.scss
Items on the side navbar had css rule of `word-wrap: break-word`, which caused unwanted word break on the UI. Remove this rule to fix this issue.
=> fix: issue with side navbar items' wordwrap
