components/Search.vue
pages/news/_slug/index.vue
pages/news/index.vue
pages/news/news.vue
pages/search/_query/index.vue
pages/tag/_query/index.vue
store/actions.js

Combines `fetchPosts` and `fetchPages` into a single function called `fetchApiData` which accepts a single parameter, `postType`, to determine which API endpoint to use.

Consolidate fetch functions for API data

---

package.json

Resolves #28, adds `npm run test` to GitHub Actions CI.
Depends on #27.

Tooling: add ESLint to CI (resolve #28)

---

components/Footer.vue
components/Header.vue
layouts/default.vue

Set up base components

---

components/Brand.vue
components/Footer.vue
components/Header.vue
layouts/default.vue

Component header brand

---

layouts/error.vue

using Article component
resolves #71

feat: simplified error-page

---

components/SearchForm.vue

Sets the `action` attribute of the search form and the name of the search input to the correct values so that searching works.
1. Check out this branch.
2. Run `npm install && npm run dev`.
3. Search for "inclusion".
**Expected behavior:** Search results are displayed.

feat: add proper action route to search form

---

.github/workflows/main.yml

Attempt to fix #84.
1. Open a PR from a fork.
**Expected behavior:** GitHub Actions run.
- Resolves #84.

feat: run actions on pull requests (resolves #84)

---

assets/css/main.css
commitlint.config.js
package-lock.json
package.json

This PR adds husky and lint-staged to run the following tasks when committing:
- Lints any modified CSS, SCSS or Vue files with stylelint
- Lints any modified JavaScript or Vue files with eslint
- Lints any modified markdown files with markdownlint
- Lints the commit message according to Conventional Commit guidelines using commitlint
1. Commit something.
**Expected behavior:** Commit should be blocked if any changed files fail validation.

feat: add precommit hooks to lint on commit

---

components/Footer.vue

This PR adds a credit for Netlify hosting in the footer.
1. View any page.
**Expected behavior:** Netlify credit link appears in the footer.
This is required for hosting on a Netlify [Open Source](https://www.netlify.com/legal/open-source-policy/) plan.

feat: credit Netlify

---

assets/config.js
components/NewsItem.vue
components/PostArticle.vue
store/actions.js

This PR updates the API endpoint to the new We Count CMS backend which is hosted at https://wecount-cms.inclusivedesign.ca.
1. Review deploy preview.
**Expected behavior:** Content matches previous site.
All user accounts from the existing WordPress site have been migrated to the new Wecount CMS site.

feat: update API endpoint to new CMS installation

---

pages/index.vue

So that the title is modifiable.
To resolve https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/125.
Repeat steps described in the issue. The problem should go away.

fix: at loading the index page, check 'slug' field rather than 'title'

---

assets/css/abstracts/_variables.scss
assets/css/components/_components.scss
assets/css/components/_news-and-views.scss
assets/css/components/_post-article.scss
components/PostArticle.vue
pages/tag/_query/index.vue
pages/views/_slug/index.vue

To resolve https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/117.
Style the single "views" page according to [the design](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website?node-id=684%3A71).
1. Run "npm run dev" and access the website at "http://localhost:3000";
2. Go to "Views";
3. Go to the views article named "Test Post for Views – 11". (This test article has content);
4. Verify the page style.
The style should match what's on the design.

Layout single views

---

assets/css/layout/_layout.scss

Resolves #147.
1. Visit "About" page.
2. Inspect image caption.
**Expected behavior:** Text colour has sufficient contrast.
Fixes #147.

fix: improve styling for image captions (fix #147)

---

package-lock.json
package.json

I figured we should run `npm update` and make sure we have incorporated any security fixes to our dependencies (there's some audit warnings on our production branch).
1. Check the deploy preview.
**Expected behavior:** Everything works as expected.

chore(deps): run npm update

---

assets/css/components/_cards.scss
components/Header.vue
components/Pagination.vue
pages/index.vue

Resolves validation errors identified in #163.
1. Validate deploy preview: https://validator.w3.org/nu/?doc=https%3A%2F%2Fdeploy-preview-165--wecount.netlify.com%2F
**Expected behavior:** Errors are resolved.
Resolve #163.

fix: resolve validation errors (fixes #163)

---

README.md

added to between "need" and "install".

---

LICENSE
package.json

Updates license to standard BSD 3-Clause license.
This repository originally used CC-BY. However, as it doesn't contain site content, it should be licensed with our standard software license. I asked @jobara about this and confirmed with @colinbdclark.

chore(docs): update license

---

src/_includes/components/grid-item.njk
src/_includes/globals/matomo-analytics.njk
src/_includes/layouts/base.njk
src/_includes/layouts/post.njk
src/tags.njk
src/views.njk

Fix all html validation errors and warnings across the site.
1. Run each site page, excluding the search page, thru [W3C HTML validator](https://validator.w3.org/);
2. No errors and warnings should be reported.
Note: [W3C HTML validator](https://validator.w3.org/) only parses static pages. The search page is a dynamically generated page that cannot be evaluated by [W3C HTML validator](https://validator.w3.org/).
See above.

fix: fix html validation errors and warnings (resolves #279)

---

src/post.njk
src/scss/components/_post-article.scss

Remove the feature image from the post page.
1. Go to "Views" page; 
2. Select a post.
The feature image should not be shown in between the post title and the content.

fix: remove the feature image from the post page (resolves #311)

---

src/_includes/globals/google-analytics.njk
src/_includes/layouts/base.njk

Remove Google Analytics and only use IDRC Mamoto tracking for the privacy.

feat: remove Google Analytics (resolves #323)

---

src/js/team-handler.js
src/page.njk
src/scss/components/_components.scss
src/scss/components/_team.scss

Create the We Count Team page.
1. Go to the URL: {domain}/team;
2. The page should match [the figma design](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website?node-id=2742%3A412);
3. Test with UIO and the page should respond properly.
See above.
Note that this page shows test data. The name of "Jutta Treviranus" is a link to a random IDRC page for testing purpose.

feat: create the we count team page (resolves #418)

---

src/js/views-dynamic-handler.js
src/views.njk

Clean up commented code and debugging lines.

chore: code clean up

---

package.json
src/admin/config.yml

Enables adding new Resources to the site via the Netlify CMS. Previews are not currently enabled
1. Log into the Netlify CMS
2. Click on "Resources"
3. Click on "New Resource"
4. Fill in the fields and click "Publish Now"
**Expected behavior:** A new resource item should be added

feat: enable resource creation

---

.github/ISSUE_TEMPLATE/a11y_issue.md
.github/ISSUE_TEMPLATE/bug_report.md

This update adds a GitHub template for accessibility issues.
N/A
N/A
N/A

feat: a11y bug template

---

package.json

Fix the failure at the build step.
1. Run `npm run build` or `npm start`
The build step should pass without any error.

fix: fix the build failure (resolves #1537)

---

.github/workflows/sync-content-changes.yml

See: https://stackoverflow.com/questions/68057744/create-pull-request-with-github-action/73340290#73340290

feat: sync content changes on changes to main branch
